### PR TITLE
electron-prebuilt upgraded to latest release

### PR DESCRIPTION
**Pull request by ppitonak**

### CODE REVIEW

**Comment by twolfson** [comment]
What's the reason behind this PR? This is a development dependency so it only affects testing. However, if we want to expand coverage of our testing with respect to Electron, then we should add tests for the past 2 major versions as well (e.g. `0.35.x`, `0.36.x`)

**Comment by twolfson** [comment]
As a heads up, this package currently chokes at requiring submodules in the same context as the same window scope.

We have patched it by switching to `window.open` in https://github.com/twolfson/karma-electron/tree/dev/fix.nested.context but that requires a patch from `karma` which is being reviewed:

https://github.com/karma-runner/karma/pull/1984

**Comment by ppitonak** [comment]
The main reason for this PR is that I consider it a good practice to test with latest stable release. In the case that Electron team supports multiple streams, it makes sense to run tests on all stable releases.

**Comment by twolfson** [comment]
I don't believe Electron offers multiple streams but we could set something up in Travis CI that does `npm install electron-prebuilt@version` based on environment variables.

That being said, I don't have time at the moment to take that on so I will land this PR as is =/

Thanks for the quick response

**Comment by twolfson** [comment]
This has been merged/released in `3.0.5` (patch release since it doesn't affect non-development usage)

**Pull request merged**
