### PR TITLE
No custom user agent

### PR DESCRIPTION
**Pull request by makarandp0**
some times the code running inside electron is generic, and may need access to real userAgent. This small change adds an option to not user custom user agent.

I have tested that it works for our scenario. Please let me know what you think about adding it to main branch.

### CODE REVIEW

**Comment by makarandp0** [comment]
@twolfson, Can you please take a look at this PR and let me know what you think about it?

**Comment by twolfson** [comment]
Sorry for the delay. On my way back from a very long vacation. I'll review
this within the next 2 weeks

**Review by twolfson — APPROVED** [review]
Looks great! Going to nitpick and rename parameter to `--default-user-agent` so the logic further down is a little less confusing (`program.customUserAgent` implies that there'd be a custom string overide)

**Comment by twolfson** [comment]
This has been released in `6.1.0`. Thanks for your help!

**Pull request merged**
